

-- Este projeto seria a criação do banco de dados de um setor de controle de qualidade de uma empresa, 
-- melhorando assim o processo de utilização de papel para computador.

-- Cada pedido de venda possui um cliente, uma qualidade, um epc (ranges de trabalho), um tipo de embalagem e muitas analises físico químicas,
-- cada cliente possui um pais de origem, cada analista possui uma função e pode fazer varias analises físico quimica.


-- Criacao do banco de dados
CREATE DATABASE CONTROLE_DE_QUALIDADE;
USE CONTROLE_DE_QUALIDADE;
CREATE TABLE QUALIDADE (
	ID_QUALIDADE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_QUALIDADE VARCHAR(50)
);
CREATE TABLE EMBALAGEM(
	ID_EMBALAGEM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TIPO_EMBALAGEM VARCHAR(50),
	VOLUME_EMBALAGEM VARCHAR(50)
);
CREATE TABLE PAIS(
	ID_PAIS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_PAIS VARCHAR(50)
);
CREATE TABLE FUNCAO(
	ID_FUNCAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TIPO_FUNCAO VARCHAR(100)
);
CREATE TABLE EPC(
	ID_EPC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DENSIDADE_MINIMA INT,
	DENSIDADE_MAXIMA INT,
	COR_MINIMA DOUBLE,
	COR_MAXIMA DOUBLE,
	UMIDADE_MINIMA DOUBLE,
	UMIDADE_MAXIMA DOUBLE,
	PH_MINIMO DOUBLE,
	PH_MAXIMO DOUBLE,
	SEDIMENTO_MINIMO INT,
	SEDIMENTO_MAXIMO INT,
	ASPECTO_MINIMO INT,
	ASPECTO_MAXIMO INT,
	AT_MINIMO DOUBLE,
	AT_MAXIMO DOUBLE,
	SENSORIAL VARCHAR(100)
);
CREATE TABLE CORRIDA(
	ID_CORRIDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUMERO_CORRIDA VARCHAR(6),
	ID_QUALIDADE INT,
	CONSTRAINT FK_CORRIDA_QUALIDADE FOREIGN KEY (ID_QUALIDADE) REFERENCES QUALIDADE (ID_QUALIDADE)
);
CREATE TABLE ANALISTA(
	ID_ANALISTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_ANALISTA VARCHAR(100),
    ID_FUNCAO INT,
    CONSTRAINT FK_ANALISTA_FUNCAO FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO (ID_FUNCAO)
);
CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    COLETA_AMOSTRAS SMALLINT(1),
    ID_PAIS INT,
    CONSTRAINT FK_CLIENTE_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS)
);
CREATE TABLE PEDIDO_DE_VENDA(
	ID_PEDIDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUMERO_PEDIDO VARCHAR(12),
    ID_CLIENTE INT,
    ID_QUALIDADE INT,
    ID_EPC INT,
    ID_EMBALAGEM INT,
    CONSTRAINT FK_PEDIDO_DE_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_PEDIDO_DE_VENDA_QUALIDADE FOREIGN KEY (ID_QUALIDADE) REFERENCES QUALIDADE (ID_QUALIDADE),
    CONSTRAINT FK_PEDIDO_DE_VENDA_EPC FOREIGN KEY (ID_EPC) REFERENCES EPC (ID_EPC),
    CONSTRAINT FK_PEDIDO_DE_VENDA_EMBALAGEM FOREIGN KEY (ID_EMBALAGEM) REFERENCES EMBALAGEM (ID_EMBALAGEM)
);
CREATE TABLE ANALISE_FISICO_QUIMICA(
	ID_FQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_PRODUCAO DATE,
    DENSIDADE INT,
    COR DOUBLE,
    UMIDADE DOUBLE,
    PH DOUBLE,
    SEDIMENTO INT,
    ASPECTO INT,
    AT DOUBLE,
    SENSORIAL VARCHAR(100),
    ID_PEDIDO INT,
    ID_CORRIDA INT,
    ID_ANALISTA INT,
    CONSTRAINT FK_ANALISE_FISICO_QUIMICA_PEDIDO_DE_VENDA FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO_DE_VENDA(ID_PEDIDO),
    CONSTRAINT FK_ANALISE_FISICO_QUIMICA_CORRIDA FOREIGN KEY (ID_CORRIDA) REFERENCES CORRIDA (ID_CORRIDA),
    CONSTRAINT FK_ANALISE_FISICO_QUIMICA_ANALISTA FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA (ID_ANALISTA)
);

-- Inserção de Dados
INSERT INTO PAIS ()
VALUES (DEFAULT,'EUA'),
(DEFAULT,'Brasil'),
(DEFAULT,'Itália'),
(DEFAULT,'Alemanha'),
(DEFAULT,'Portugal'),
(DEFAULT,'Suiça');

-- Atualização do bd
UPDATE PAIS
set NOME_PAIS = 'Argentina'
WHERE ID_PAIS = 1;

-- Exlusão de Dados da Tabela
DELETE FROM PAIS WHERE ID_PAIS = 5;

SELECT *
FROM PAIS
WHERE ID_PAIS = 2;

SELECT *
FROM PAIS;





 