-- aula 11

USE FILMES_DB;

SELECT *
FROM FILMES;

-- ALIAS
--  SERIA PARA RENOMEAR LAGO, NESTE EXEMPLO A TABELA FILMES
SELECT F.TITULO
FROM FILMES AS F;

-- PARA RENOMEAR A COLUNA TITULO
SELECT 
TITULO AS FILMES
FROM FILMES;

-- OU PARA COLOCAR MAIS DE UM NOME DEVERÁ SER INSERIDO AS ""
SELECT TITULO AS 'THE BEST DOS FILMES'
FROM FILMES;

-- ORDER BY

-- SERIA PARA ORDENAR A TABELA PELO TITULO (POR PADRÃO VEM O TIPO ASC, ENTRETANTO CASO QUEIRA 
-- PODERÁ SER ALTERADO PARA desc
SELECT TITULO
FROM FILMES
ORDER BY TITULO DESC;


-- NO CASO ABAIXO ELE IRÁ ORDENAR PRIMEIRO PELO ID E DEPOIS PELO TITULO, CASO TENHA DOIS DADOS IGUAIS

SELECT TITULO,ID
FROM FILMES
ORDER BY 
ID DESC,
TITULO DESC;

SELECT *
FROM FILMES;

-- PARA ALTERAR O FORMATO DO MES PARA O PADRÃO BRASILEIRO

SELECT DATE_FORMAT(`DATA_LANCAMENTO`, "%d %M %Y")
FROM FILMES;

-- GROUP BY PARA QTDD DE REPETIÇÕES

USE MUSIMUNDOS;

SELECT * 
FROM CLIENTES;

SELECT 
PAIS,
COUNT(*) AS 'QTDD DE REPETIÇÕES'
FROM CLIENTES
GROUP BY PAIS
ORDER BY PAIS;

-- HAVING PARA TRAZER OS REGISTROS QUE SE REPETEM MAIS QUE 5X

USE MUSIMUNDOS;

SELECT 
PAIS,
COUNT(*) AS 'QTDD DE REPETIÇÕES'
FROM CLIENTES
GROUP BY PAIS
HAVING COUNT(*) >= 5 -- VAI TRAZER TODOS QUE OBTEREM MAIS DO QUE 5 REPETIÇÕES
ORDER BY PAIS;

