USE MUSIMUNDOS;
-- 1-TODOS OS CLIENTES CADASTRADOS
SELECT *
FROM CLIENTES;

-- 2.TODOS OS CLIENTES DO USA
SELECT *
FROM CLIENTES
WHERE PAIS = 'USA';

-- 3.RELATORIO DE MUSICAS COM BETWEEN
SELECT *
FROM CANCOES
WHERE DURACAO_MILISEGUNDOS BETWEEN 200000 AND 300000; 

-- 4. CLIENTES ESPANHA OU ARGENTINA
SELECT *
FROM CLIENTES
WHERE PAIS = 'BRAZIL';


-- QTDD DE CANCOES COM O GENERO 6
SELECT COUNT(ID_GENERO)
FROM CANCOES
WHERE ID_GENERO = 6;

-- SOMA DO VALOR DE TODAS NF 
SELECT SUM(VALOR_TOTAL)
FROM FATURAS;

-- MEDIA DA DURAÇÃO DAS CANCÕES DO ID 4
SELECT AVG(DURACAO_MILISEGUNDOS) 
FROM CANCOES 
WHERE ID_ALBUM = 4;

-- MENOR PESO
SELECT MIN(BYTES)
FROM CANCOES
WHERE BYTES;

SELECT SUM(VALOR_TOTAL) 
FROM FATURAS 
WHERE ID_CLIENTE = 6;


