use musimundos;

SELECT *
FROM FATURAS;

-- 1 - O VALOR DA FATURA MAIS ALTA CUJO A CIDADE DE COBRANÇA É OSLO
SELECT MAX(VALOR_TOTAL)
FROM FATURAS
WHERE CIDADE_COBRANCA = 'OSLO';

-- 2- O VALOR DA FATURA MAIS BAIXA DE TODAS
SELECT MIN(VALOR_TOTAL)
FROM FATURAS;

-- 3. O VALOR MEDIO DAS FATURAS QUE O PAIS DE COBRANÇA É CANADA

SELECT AVG(VALOR_TOTAL)
FROM FATURAS
WHERE PAIS_COBRANCA = 'CANADÁ';

-- 4. A QTDD DE FATURAS QUE O PAIS DE COBRANCA É CANADA

SELECT COUNT(ID)
FROM FATURAS
WHERE PAIS_COBRANCA = 'CANADÁ';

-- 5. O VALOR TOTAL SOMADO DE TODAS AS FATURAS
SELECT SUM(VALOR_TOTAL)
FROM FATURAS;

-- 6. SELECIONE O ID, A DATA E VALOR DAS FATURAS COM VALOR ABAIXO DA MEDIA
SELECT ID,DATA_FATURA,VALOR_TOTAL
FROM FATURAS
WHERE VALOR_TOTAL < (SELECT AVG(VALOR_TOTAL) FROM FATURAS);

-- 15. QTDD DE CLIENTES QUE TENHAM O EMAIL DO YAHOO
SELECT *
FROM CLIENTES;

SELECT COUNT(ID)
FROM clientes
WHERE EMAIL LIKE '%YAHOO%';
